[package]
name = "dotman"
version = "0.0.6"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
jsonnet = ["jsonnet-rs"]
network = ["reqwest"]

[dependencies]
anyhow = "1.0.44"
clap = { version="3.0.0-beta.5", features=["derive"] }
duct = "0.13.5"
hex = "0.4.3"
hostname = "0.3.1"
jsonnet-rs = { version="0.17.0", optional = true }
kstring = "1.0.5"
libc = "0.2.105"
liquid = "0.23.0"
maplit = "1.0.2"
md5 = "0.7.0"
nom = "7.0.0"
once_cell = "1.8.0"
regex = "1.5.4"
reqwest = { version="0.11.6", features=["blocking", "rustls-tls"], default-features=false, optional=true }
sha2 = "0.9.8"
termion = "1.5.6"
thiserror = "1.0.30"
yaml-rust = "0.4.5"
