# basic
# 補完で有名なやつ
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install --frozen-lockfile'
merged = 0

# ファイルとかをいい感じに探せる有名なやつ
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
'''

# deniteにヤンク履歴を残すやつ
[[plugins]]
repo = 'Shougo/neoyank.vim'

# 左側にディレクトリツリーを出せる
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
'''

# コード片を実行できる。けどあんまり使ってない
[[plugins]]
repo = 'thinca/vim-quickrun'

# 特定の単語をハイライトできる。便利
[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
	nmap <Space>m <Plug>(quickhl-manual-this)
	xmap <Space>m <Plug>(quickhl-manual-this)
	nmap <Space>M <Plug>(quickhl-manual-reset)
	xmap <Space>M <Plug>(quickhl-manual-reset)
'''

# 所謂powerline
[[plugins]]
repo = 'itchyny/lightline.vim'

# 構文チェッカ
[[plugins]]
repo = 'w0rp/ale'

# 検索位置表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_pos_source = '''
" mapping
	nmap n <Plug>(anzu-n-with-echo)
	nmap N <Plug>(anzu-N-with-echo)
	nmap * <Plug>(anzu-star-with-echo)
	nmap # <Plug>(anzu-sharp-with-echo)

	" clear status
	nmap <Esc><Esc> <Plug>(anzu-clear-search-status)

	" statusline
	set statusline=%{anzu#search_status()}
'''

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# 表整形
[[plugins]]
repo = 'junegunn/vim-easy-align'

# languages
## TypeScript or JavaScript
[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
hook_add = '''
'''
on_ft = 'typescript'

[[plugins]]
repo ='posva/vim-vue'
on_ft = 'vue'

# TeX
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
	let g:vimtex_indent_enabled=0
	let g:vimtex_compiler_progname='nvr'
'''

# satysfi
[[plugins]]
repo = 'ToruNiina/satysfi.vim'
on_ft = 'satysfi'

# Elm
[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = 'elm'

# Pug
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

# Elixir
[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Rust

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
	let g:rustfmt_autosave = 1
	nnoremap <Space>t :RustTest!<CR>
'''

# OpenSCAD
[[plugins]]
repo = 'sirtaj/vim-openscad'

# Clojure
[[plugins]]
repo = 'tpope/vim-fireplace'
on_ft = 'clojure'

# fish
[[plugins]]
repo = 'dag/vim-fish'

# colorscheme
[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'KabbAmine/yowish.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'wimstefan/vim-artesanal'

[[plugins]]
repo = 'vim-scripts/Gummybears'

[[plugins]]
repo = 'scottymoon/vim-twilight'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'gregjurman/vim-nc'
