AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/GlobalVars:
  Enabled: false
