complete -c platformio -f

complete -c platformio      -l version -n '__fish_arg_len_is_zero' -d 'Show the version and exit.'
complete -c platformio -s f -l force                                      -d 'Force to accept any confirmation prompts.'
complete -c platformio -s c -l coller                                     -d 'Caller ID (service).'
complete -c platformio -s h -l help    -n '__fish_arg_len_is_zero' -d 'Show this message and exit.'

complete -c platformio -a account      -n '__fish_arg_len_is_zero' -d 'Manage PIO Account'
complete -c platformio -a boards       -n '__fish_arg_len_is_zero' -d 'Embedded Board Explorer'
complete -c platformio -a ci           -n '__fish_arg_len_is_zero' -d 'Continuous Integration'
complete -c platformio -a debug        -n '__fish_arg_len_is_zero' -d 'PIO Unified Debugger'
complete -c platformio -a device       -n '__fish_arg_len_is_zero' -d 'Monitor device or list existing'
complete -c platformio -a home         -n '__fish_arg_len_is_zero' -d 'PIO Home'
complete -c platformio -a init         -n '__fish_arg_len_is_zero' -d 'Initialize PlatformIO project or update existing'
complete -c platformio -a lib          -n '__fish_arg_len_is_zero' -d 'Library Manager'
complete -c platformio -a platform     -n '__fish_arg_len_is_zero' -d 'Platform Manager'
complete -c platformio -a remote       -n '__fish_arg_len_is_zero' -d 'PIO Remote'
complete -c platformio -a run          -n '__fish_arg_len_is_zero' -d 'Process project environments'
complete -c platformio -a settings     -n '__fish_arg_len_is_zero' -d 'Manage PlatformIO settings'
complete -c platformio -a test         -n '__fish_arg_len_is_zero' -d 'Local Unit Testing'
complete -c platformio -a update       -n '__fish_arg_len_is_zero' -d 'Update installed platforms, packages and libraries'
complete -c platformio -a upgrade      -n '__fish_arg_len_is_zero' -d 'Upgrade PlatformIO to the latest version'
