version: 2
jobs:
  build:
    docker:
      - image: namachan10777/scripts:latest

    steps:
      - checkout
      - run:
          name: test
          command: |
            fish ./install.fish
            fish ~/.dotfiles/bin/test.fish

