version: 2
jobs:
  build:
    docker:
      - image: namachan10777/scripts:latest

    steps:
      - checkout
      - run:
          name: test
          command: |
            make install
            make install-system
