XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache

ZSH_CONFIG_HOME=$HOME/.zsh
ZSH_FOREIGN_PACKAGE_HOME=$XDG_CACHE_HOME/zsh_foreign_package

export XDG_CONFIG_HOME
OCAMLPARAM="_,bin-annot=1"
OPAMKEEPBUILDDIR=1
export OCAMLPARAM
export OPAMKEEPBUILDDIR

eval `opam config env`
