[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
	on_event = 'InsertCharPre'
	hook_add = '''
		let g:deoplete#enable_at_startup = 1
		let g:deoplete#auto_complete_delay = 0
		let g:deoplete#auto_complete_start_length = 1
		let g:deoplete#enable_camel_case = 0
		let g:deoplete#enable_inogre_case = 0
		let g:deoplete#enable_refresh_always = 0
		let g:deoplete#enable_smart_case = 1
		let g:deoplete#file#enable_buffer_path = 1
		let g:deoplete#max_list = 10000
		call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
		inoremap <silent><expr> <TAB>
			\ pumvisible() ? "\<C-n>" :
			\ "\<TAB>"
	'''
	on_i = 1

[[plugins]]
repo = 't9md/vim-quickhl'
	hook_add = '''
		nmap <Space>m <Plug>(quickhl-manual-this)
		xmap <Space>m <Plug>(quickhl-manual-this)
		nmap <Space>M <Plug>(quickhl-manual-reset)
		xmap <Space>M <Plug>(quickhl-manual-reset)
	'''

[[plugins]]
repo = 'dag/vim-fish'
	hook_add = '''
		compiler fish
	'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
	hook_add = '''
		let g:unite_source_history_yank_enable=1
		nnoremap <silent> ,uy :<C-u>Unite history/yank<CR>
	'''

[[plugins]]
repo = 'scrooloose/nerdtree'
	hook_add = '''
		nnoremap <silent> ,ne :NERDTreeToggle<CR>
		nnoremap <silent> ,n :NERDTreeCWD<CR>
	'''
