# basic
# 補完で有名なやつ
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_add = '''
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#auto_complete_delay = 0
	let g:deoplete#auto_complete_start_length = 1
	let g:deoplete#enable_camel_case = 0
	let g:deoplete#enable_inogre_case = 0
	let g:deoplete#enable_refresh_always = 0
	let g:deoplete#enable_smart_case = 1
	let g:deoplete#file#enable_buffer_path = 1
	let g:deoplete#max_list = 10000
	let g:deoplete#min_pattern_length = 2
	call deoplete#custom#source('_', 'matchers', ['matcher_full_fuzzy'])
	inoremap <silent><expr> <TAB>
		\ pumvisible() ? "\<C-n>" :
		\ "\<TAB>"
'''
on_i = 1

# ファイルとかをいい感じに探せる有名なやつ
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
'''

# deniteにヤンク履歴を残すやつ
[[plugins]]
repo = 'Shougo/neoyank.vim'

# 左側にディレクトリツリーを出せる
[[plugins]]
repo = 'scrooloose/nerdtree'

# コード片を実行できる。けどあんまり使ってない
[[plugins]]
repo = 'thinca/vim-quickrun'

# 特定の単語をハイライトできる。便利
[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
	nmap <Space>m <Plug>(quickhl-manual-this)
	xmap <Space>m <Plug>(quickhl-manual-this)
	nmap <Space>M <Plug>(quickhl-manual-reset)
	xmap <Space>M <Plug>(quickhl-manual-reset)
'''

# 所謂powerline
[[plugins]]
repo = 'itchyny/lightline.vim'

# LSP
#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#hook_add = '''
#	let g:LanguageClient_serverCommands = {
#		\ 'rust': ['~/.cargo/bin/rustup', 'run', 'nightly', 'rls'],
#	\}
#'''

# 構文チェッカ
[[plugins]]
repo = 'w0rp/ale'

# languages
## TypeScript or JavaScript
[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
hook_add = '''
'''
on_ft = 'typescript'

[[plugins]]
repo ='posva/vim-vue'
on_ft = 'vue'

# TeX
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

# satysfi
[[plugins]]
repo = 'ToruNiina/satysfi.vim'
on_ft = 'satysfi'

# Elm
[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = 'elm'

# Pug
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

# Elixir
[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Rust
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_add = '''
	let g:deoplete#sources#rust#racer_binary='/home/namachan/.cargo/bin/racer'
	let g:deoplete#sources#rust#rust_source_path='/home/namachan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src'
	let g:deoplete#sources#rust#show_dupliates = 1
	let g:deoplete#sources#rust#disable_keymap = 1
	nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
	nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
	let g:rustfmt_autosave = 1
	nnoremap <Space>t :RustTest!<CR>
'''

# colorscheme
[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'KabbAmine/yowish.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'wimstefan/vim-artesanal'
