name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install -y fish
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Run test
      run: |
        mkdir ~/.config
        python --version
        python ./bin/deploy.py -d ./config.json
        python ./bin/deploy.py -c ./config.json
